### ISSUE TITLE
[Bug] Cannot create label

### ISSUE THREAD

**Issue by stephanboersma** [CoolRunner-dk/smartcheckout-woocommerce#1]
Hi,

I cannot create a label for my order. Everything is set up per instructions. The shipping option and prices are showing correctly to the customers.

I tried to create a label from the "Edit order" page and then it updated and nothing happened. The order notes now had "Fejl Coolrunner:".
<img width="286" alt="Skærmbillede 2021-04-25 kl  16 55 23" src="https://user-images.githubusercontent.com/32750681/115998429-6d9d8400-a5e7-11eb-9d92-94631a4cbd5c.png">

In CoolRunner I can see a new Order but when I can't find the equivalent label for my shipment.
<img width="1050" alt="Skærmbillede 2021-04-25 kl  16 59 00" src="https://user-images.githubusercontent.com/32750681/115998468-a76e8a80-a5e7-11eb-92ae-28787cc7056a.png">

I am using the newest version of woocommerce (5.7.1).

Is this a bug or a mistake on my end? :)

Looking forward to be hearing from you.

Best regards,
Stephan Boersma
metalvinyl.dk

**Comment by KevinSHansen** [comment]
Hi Stephan,

Thanks for reporting this issue. You meet this issue because there is no payment method added to your account.

That can be done on CoolRunner.dk > My account.

--

We will look into returning this error message. Thanks for the headsup.
